# Generated by Django 4.0.2 on 2022-02-10 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='edad',
            new_name='age',
        ),
    ]
