# Generated by Django 4.0.2 on 2022-02-10 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usermodel_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='age',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
    ]
